services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    container_name: postgres_test
    env_file:
      - .env.test
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    networks:
      network_psql:
        ipv4_address: 172.60.0.2

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin_test
    env_file:
      - .env.test
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      network_psql:
        ipv4_address: 172.60.0.3

networks:
  network_psql:
    driver: bridge
    ipam:
      config:
        - subnet: 172.60.0.0/24
          gateway: 172.60.0.1

volumes:
  db_data:
  pgadmin_data: