services:
  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - data:/var/lib/rabbitmq/
      - log:/var/log/rabbitmq
    env_file:
      - .env.test

volumes:
  log:
  data: