version: '3.8'

services:
  wordpress:
      image: wordpress:php8.4-apache
      container_name: wordpress_test
      env_file:
        - .env.test      
      volumes:
        - ./wordpress_data:/var/www/html
        - ./php-config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      ports:
        - "8001:80"
        - "8002:443"
      depends_on:
        - mysql_db
      networks:
        - app_network
  
  mysql_db:
    image: mysql:8.0

    env_file:
      - .env.test
    container_name: mysql_db
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"
    networks:
      - app_network
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_proxy
    container_name: nginx_test
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - nginx_volume:/etc/nginx/conf.d
      # - nginx_volume/default.conf:/etc/nginx/conf.d/default.conf:ro      
      - ./nginx_conf/default.conf:/etc/nginx/conf.d/default.conf:ro      
      - ./nginx_ssl:/etc/nginx/ssl/
      - static_volume:/var/www/static
      - media_volume:/var/www/media
    depends_on:
      - django_app
    networks:
      - app_network
    restart: unless-stopped

volumes:
  mysql_data:
  wordpress_data:
  nginx_conf:
  static_volume:
  media_volume:

networks:
  app_network:
    driver: bridge
  
