version: '3.3' 
services:  
  mongoserver:
    image: mongo:latest 
    container_name: mongoserver
    env_file:
      - .env.test
    ports:
      - "27017:27017" 
    volumes:
      - mongodb_data:/data/db 
    restart: always 
  
  mongo-express:
    image: mongo-express:latest 
    container_name: mongoexpress
    env_file:
      - .env.test    
    ports:
      - "8081:8081"
    depends_on:
      - mongoserver
    restart: always 
volumes:
  mongodb_data: 
    driver: local 