version: '3.3' 
services:  
  mongodb:
    image: mongo:latest 
    container_name: dev_mongodb 
    ports:
      - "27017:27017" 
    volumes:
      - mongodb_data:/data/db 
    restart: always 
  
  mongo-express:
    image: mongo-express:latest 
    container_name: dev_mongo_express 
    ports:
      - "8081:8081"
    depends_on:
      - mongodb 
    restart: always 
volumes:
  mongodb_data: 
    driver: local 